/*------------------------------------------------------------------------------
MASV: 1412503
HỌ TÊN: NGUYỄN THỊ THANH THẢO
LAB: 03
NGÀY: 31/5/2017
--------------------------------------------------------------------------------*/
--create database QLSV

use QLSV

/*------------------------------------------------------------------------------
MASV: 1412503
HỌ TÊN: NGUYỄN THỊ THANH THẢO
LAB: 03
NGÀY: 31/5/2017
--------------------------------------------------------------------------------*/
CREATE TABLE SINHVIEN(
	MASV NVARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL, 
	MATKHAU VARBINARY(1000) NOT NULL
)

CREATE TABLE NHANVIEN(
	MANV VARCHAR (20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY(1000),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(1000) NOT NULL
)

CREATE TABLE LOP(
	MALOP VARCHAR(20) PRIMARY KEY,
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20)
)

ALTER TABLE SINHVIEN
ADD CONSTRAINT FK_SINHVIEN_LOP
FOREIGN KEY (MALOP)
REFERENCES LOP(MALOP)

ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_NHANVIEN
FOREIGN KEY (MANV)
REFERENCES NHANVIEN(MANV)

GO
CREATE PROC SP_INS_ENCRYPT_SINHVIEN @MASV NVARCHAR(20), @HOTEN NVARCHAR(100), @NGAYSINH DATETIME, @DIACHI NVARCHAR(200), @MALOP VARCHAR(20), @TENDN NVARCHAR(100), @MATKHAU VARBINARY(100)
AS
BEGIN
	INSERT INTO SINHVIEN VALUES (@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, @MATKHAU)
END

GO
CREATE PROC SP_INS_ENCRYPT_NHANVIEN @MANV VARCHAR(20), @HOTEN NVARCHAR(100), @EMAIL  VARCHAR(20), @LUONG VARBINARY(100), @TENDN NVARCHAR(100), @MATKHAU VARBINARY(100)
AS
BEGIN
	INSERT INTO NHANVIEN VALUES (@MANV, @HOTEN, @EMAIL, @LUONG, @TENDN, @MATKHAU)
END

GO
CREATE PROC SP_SEL_ENCRYPT_NHANVIEN 
AS
BEGIN
	SELECT MANV, HOTEN, EMAIL, LUONG FROM NHANVIEN
END




